# ---- Segmentation-free analysis of transcript coordinates (experimental) ----
#
# Transcripts of each gene are treated as a log-Gaussian Cox process (LGCP).
# The log-intensity is a linear combination of a shared "cell density" field
# and K spatial factors, each a Gaussian process approximated with random
# Fourier features (RFF; Rahimi & Recht 2008), following the random-feature
# latent variable model of Gundersen, Zhang & Engelhardt (AISTATS 2021) with
# the spatial coordinates as the (observed) inputs.
#
# Co-localization of two gene sets is summarized by the LGCP cross pair
# correlation g_AB(r), available in closed form from the fitted model and
# estimable model-free from binned counts (pcf_cross()).

# ---- Simulation -------------------------------------------------------------

# Internal: stationary Gaussian random field with an RBF covariance
# exp(-h^2 / (2 ell^2)) on an nx x ny grid (spacing delta), unit variance,
# generated by FFT on a padded torus.
.grf_fft <- function(nx, ny, delta, ell) {
  px <- stats::nextn(2 * nx + ceiling(4 * ell / delta))
  py <- stats::nextn(2 * ny + ceiling(4 * ell / delta))
  freq <- function(p) {
    k <- 0:(p - 1)
    ifelse(k < p / 2, k, k - p) * 2 * pi / (p * delta)
  }
  kx <- freq(px)
  ky <- freq(py)
  S <- exp(-0.5 * ell^2 * outer(kx^2, ky^2, "+"))
  noise <- matrix(stats::rnorm(px * py), px, py)
  raw <- Re(stats::fft(stats::fft(noise) * sqrt(S), inverse = TRUE))
  raw[seq_len(nx), seq_len(ny)] / sqrt(px * py * sum(S))
}

#' Simulate transcript coordinates from a multivariate log-Gaussian Cox process
#'
#' **Experimental.** Genes are organized in gene
#' sets (e.g. marker genes of cell types). The log-intensity of gene `j` in
#' set `S` at location `u` is
#' \deqn{\log\lambda_j(u) = \log\rho + \sigma_d d(u) + \sigma_s f_S(u) + c_S n(u),}
#' where `d` is a shared cellularity field, `f_S` a set-specific territory
#' field and `n` a "niche" field shared by the sets in `coloc`. All fields are
#' unit-variance Gaussian random fields with an RBF covariance, generated
#' exactly by FFT (not with random features). Transcripts are Poisson counts
#' on a `resolution` grid, placed uniformly within each grid cell.
#'
#' @param gene_sets Character vector of gene-set names.
#' @param n_genes_per_set Number of genes in each set.
#' @param size Side length of the square window (micrometres).
#' @param resolution Simulation grid spacing (micrometres).
#' @param rate Baseline transcripts per square micrometre per gene.
#' @param density_sd,density_lengthscale SD and length scale of the shared
#'   cellularity field.
#' @param set_sd,set_lengthscale SD and length scale of the set-specific fields.
#' @param coloc Named numeric vector of niche loadings, e.g.
#'   `c(A = 0.8, B = 0.8)` makes sets A and B co-localize; opposite signs make
#'   them segregate.
#' @param niche_lengthscale Length scale of the niche field.
#' @param seed Random seed.
#'
#' @return A data.frame with columns `x`, `y`, `gene`, `gene_set`, carrying an
#'   attribute `truth` (the generating parameters) usable with
#'   [lgcp_true_pair_correlation()].
#' @export
#' @examples
#' tx <- simulate_transcripts(size = 150, rate = 0.01, coloc = c(A = 1, B = 1))
#' head(tx)
#' table(tx$gene_set)
simulate_transcripts <- function(gene_sets = c("A", "B", "C"),
                                 n_genes_per_set = 5,
                                 size = 500,
                                 resolution = 2,
                                 rate = 0.02,
                                 density_sd = 0.5,
                                 density_lengthscale = 80,
                                 set_sd = 1,
                                 set_lengthscale = 15,
                                 coloc = c(A = 0.8, B = 0.8),
                                 niche_lengthscale = 20,
                                 seed = 1) {
  .seed_rng(seed)
  n <- ceiling(size / resolution)
  d <- .grf_fft(n, n, resolution, density_lengthscale)
  niche <- .grf_fft(n, n, resolution, niche_lengthscale)
  genes <- paste0(rep(gene_sets, each = n_genes_per_set), "_",
                  rep(seq_len(n_genes_per_set), length(gene_sets)))
  set_of <- rep(gene_sets, each = n_genes_per_set)
  cs <- stats::setNames(rep(0, length(gene_sets)), gene_sets)
  cs[intersect(names(coloc), gene_sets)] <- coloc[intersect(names(coloc), gene_sets)]
  cell_area <- resolution^2
  out <- vector("list", length(gene_sets))
  for (k in seq_along(gene_sets)) {
    f_s <- .grf_fft(n, n, resolution, set_lengthscale)
    loglam <- log(rate) + density_sd * d + set_sd * f_s + cs[[k]] * niche
    for (g in genes[set_of == gene_sets[k]]) {
      cnt <- stats::rpois(n * n, exp(loglam) * cell_area)
      idx <- rep(seq_len(n * n), cnt)
      ix <- (idx - 1) %% n
      iy <- (idx - 1) %/% n
      out[[length(out) + 1L]] <- data.frame(
        x = (ix + stats::runif(length(idx))) * resolution,
        y = (iy + stats::runif(length(idx))) * resolution,
        gene = g, gene_set = gene_sets[k], stringsAsFactors = FALSE
      )
    }
  }
  tx <- do.call(rbind, out)
  tx <- tx[tx$x < size & tx$y < size, , drop = FALSE]
  rownames(tx) <- NULL
  attr(tx, "truth") <- list(
    gene_sets = gene_sets, genes = genes, set_of = set_of, rate = rate,
    density_sd = density_sd, density_lengthscale = density_lengthscale,
    set_sd = set_sd, set_lengthscale = set_lengthscale,
    coloc = cs, niche_lengthscale = niche_lengthscale, size = size
  )
  tx
}

#' Simulate a multi-sample case-control transcript dataset
#'
#' **Experimental.** Calls
#' [simulate_transcripts()] for every sample, with a group-specific niche
#' loading for the co-localizing gene sets plus patient-level noise.
#'
#' @param n_samples_per_group Number of samples (patients) per group.
#' @param group_coloc Named list, one numeric niche loading per group, applied
#'   to every set in `coloc_sets`, e.g. `list(control = 0.3, case = 0.9)`.
#' @param coloc_sets Gene sets that share the niche field.
#' @param between_sample_sd SD of the per-sample noise on the niche loading.
#' @param seed Random seed.
#' @param ... Passed to [simulate_transcripts()].
#'
#' @return A data.frame as [simulate_transcripts()] with `sample_id`,
#'   `group` and `patient` columns.
#' @export
#' @examples
#' tx <- simulate_transcripts_groups(n_samples_per_group = 2, size = 120,
#'                                   rate = 0.01)
#' table(tx$sample_id, tx$group)
simulate_transcripts_groups <- function(n_samples_per_group = 4,
                                        group_coloc = list(control = 0.3, case = 0.9),
                                        coloc_sets = c("A", "B"),
                                        between_sample_sd = 0.1,
                                        seed = 1, ...) {
  .seed_rng(seed)
  groups <- names(group_coloc)
  if (is.null(groups) || any(groups == "")) stop("group_coloc must be a named list.")
  out <- list()
  for (g in groups) {
    for (s in seq_len(n_samples_per_group)) {
      sid <- paste0(g, "_", s)
      cval <- group_coloc[[g]] + stats::rnorm(1, sd = between_sample_sd)
      tx <- simulate_transcripts(coloc = stats::setNames(rep(cval, length(coloc_sets)), coloc_sets),
                                 seed = sample.int(.Machine$integer.max, 1), ...)
      tx$sample_id <- sid
      tx$group <- g
      tx$patient <- sid
      out[[sid]] <- tx
    }
  }
  res <- do.call(rbind, out)
  rownames(res) <- NULL
  res
}

#' True cross pair correlation of a simulated LGCP
#'
#' Closed-form cross pair correlation between two gene sets for data from
#' [simulate_transcripts()], for validating [pcf_cross()] and
#' [rff_pair_correlation()]. See [rff_pair_correlation()] for the three
#' types.
#'
#' @param truth The `truth` attribute of a [simulate_transcripts()] result.
#' @param set_a,set_b Gene-set names.
#' @param r Distances (micrometres).
#' @param type `"relative"`, `"full"` or `"composition"`.
#'
#' @return A data.frame with `r`, `g` and `log_g`.
#' @export
#' @examples
#' tx <- simulate_transcripts(size = 100, rate = 0.01)
#' lgcp_true_pair_correlation(attr(tx, "truth"), "A", "B", r = c(5, 10, 20))
lgcp_true_pair_correlation <- function(truth, set_a, set_b, r,
                                       type = c("relative", "full", "composition")) {
  type <- match.arg(type)
  k <- function(ell) exp(-r^2 / (2 * ell^2))
  sets <- truth$gene_sets
  cs <- truth$coloc
  # set-level log-intensity cross-covariance (genes within a set are identical)
  Cset <- function(a, b, density = TRUE) {
    C <- cs[[a]] * cs[[b]] * k(truth$niche_lengthscale)
    if (identical(a, b)) C <- C + truth$set_sd^2 * k(truth$set_lengthscale)
    if (density) C <- C + truth$density_sd^2 * k(truth$density_lengthscale)
    C
  }
  if (type == "composition") {
    C <- Cset(set_a, set_b, density = FALSE)
    return(data.frame(r = r, g = exp(C), log_g = C))
  }
  g_ab <- exp(Cset(set_a, set_b))
  if (type == "full") return(data.frame(r = r, g = g_ab, log_g = log(g_ab)))
  # all transcripts: weight sets by their expected intensity
  w <- exp(0.5 * (truth$set_sd^2 + cs[sets]^2))
  w <- w * table(truth$set_of)[sets]
  w <- w / sum(w)
  g_tt <- 0
  for (a in sets) for (b in sets) g_tt <- g_tt + w[[a]] * w[[b]] * exp(Cset(a, b))
  g <- g_ab / g_tt
  data.frame(r = r, g = g, log_g = log(g))
}

# ---- Reading ----------------------------------------------------------------

#' Read a Xenium transcript table
#'
#' **Experimental.** Read `transcripts.parquet` (or `transcripts.csv.gz`)
#' from a Xenium output folder into a plain data.frame with columns `x`, `y`,
#' `z`, `gene`, `qv` (plus `cell_id` / `overlaps_nucleus` when present),
#' ready for [bin_transcripts()]. Handles older outputs in which
#' `feature_name` is stored as a binary column, filters on the Phred-scaled
#' quality `qv`, and drops negative-control and unassigned probes.
#'
#' @param path A Xenium output folder or the path of the transcript file.
#' @param qv_min Minimum `qv` to keep (10x recommends 20). `NULL` keeps all.
#' @param drop_controls Drop features whose names start with `NegControl`,
#'   `BLANK`, `Unassigned`, `Deprecated`, `antisense` or `Intergenic`.
#' @param bbox Optional `c(xmin, xmax, ymin, ymax)` crop, applied while
#'   reading.
#'
#' @return A data.frame.
#' @export
#' @examples
#' \dontrun{
#' tx <- read_xenium_transcripts("Xenium_V1_FF_Mouse_Brain_Coronal_Subset_CTX_HP_outs")
#' b <- bin_transcripts(tx, bin_size = 4)
#' }
read_xenium_transcripts <- function(path, qv_min = 20, drop_controls = TRUE, bbox = NULL) {
  if (!requireNamespace("arrow", quietly = TRUE)) {
    stop("read_xenium_transcripts() requires the 'arrow' package.")
  }
  file <- path
  if (dir.exists(path)) {
    cand <- file.path(path, c("transcripts.parquet", "transcripts.csv.gz", "transcripts.csv"))
    cand <- cand[file.exists(cand)]
    if (!length(cand)) stop("No transcripts.parquet / transcripts.csv.gz in ", path)
    file <- cand[1]
  }
  tbl <- if (grepl("\\.parquet$", file)) {
    arrow::read_parquet(file, as_data_frame = FALSE)
  } else {
    arrow::read_csv_arrow(file, as_data_frame = FALSE)
  }
  # older Xenium outputs store strings as binary: cast them to UTF-8
  for (nm in intersect(c("feature_name", "cell_id"), names(tbl))) {
    if (inherits(tbl[[nm]]$type, "Binary") || tbl[[nm]]$type$ToString() %in% c("binary", "large_binary")) {
      tbl[[nm]] <- tbl[[nm]]$cast(arrow::utf8())
    }
  }
  df <- as.data.frame(tbl)
  out <- data.frame(x = df$x_location, y = df$y_location,
                    gene = as.character(df$feature_name), stringsAsFactors = FALSE)
  if ("z_location" %in% names(df)) out$z <- df$z_location
  if ("qv" %in% names(df)) out$qv <- df$qv
  for (nm in intersect(c("cell_id", "overlaps_nucleus"), names(df))) out[[nm]] <- df[[nm]]
  keep <- rep(TRUE, nrow(out))
  if (!is.null(qv_min) && "qv" %in% names(out)) keep <- keep & out$qv >= qv_min
  if (drop_controls) {
    keep <- keep & !grepl("^(NegControl|BLANK|Unassigned|Deprecated|antisense|Intergenic)", out$gene)
  }
  if (!is.null(bbox)) {
    keep <- keep & out$x >= bbox[1] & out$x <= bbox[2] & out$y >= bbox[3] & out$y <= bbox[4]
  }
  out <- out[keep, , drop = FALSE]
  rownames(out) <- NULL
  out
}

# ---- Binning ----------------------------------------------------------------

#' Bin transcript coordinates on a square grid
#'
#' **Experimental.** Count transcripts per gene
#' in square bins, without cell segmentation. Every grid bin in the bounding
#' box is kept (so that the grid can be used with FFTs), and an `in_tissue`
#' flag marks bins close to at least one transcript.
#'
#' @param tx A data.frame of transcripts, e.g. from Xenium
#'   `transcripts.parquet` or [simulate_transcripts()].
#' @param bin_size Bin side length (same unit as the coordinates, usually
#'   micrometres).
#' @param x_col,y_col,gene_col Column names of coordinates and gene.
#' @param genes Genes to keep (default: all). Control probes such as
#'   `NegControl*` / `BLANK*` should be dropped here.
#' @param qv_col,qv_min Optional quality column and minimum value (Xenium:
#'   `qv`, 20).
#' @param bbox Optional bounding box `c(xmin, xmax, ymin, ymax)`.
#' @param tissue_radius Bins within this many bins of a transcript are
#'   flagged `in_tissue`. `Inf` flags every bin.
#'
#' @return An object of class `binned_transcripts`: a list with `counts`
#'   (sparse bins x genes matrix), `coords` (bin centres and `in_tissue`),
#'   `grid` (`nx`, `ny`, `bin_size`, `xmin`, `ymin`) and `genes`.
#' @export
#' @examples
#' tx <- simulate_transcripts(size = 100, rate = 0.01)
#' b <- bin_transcripts(tx, bin_size = 5)
#' dim(b$counts)
bin_transcripts <- function(tx, bin_size = 4, x_col = "x", y_col = "y",
                            gene_col = "gene", genes = NULL,
                            qv_col = NULL, qv_min = 20, bbox = NULL,
                            tissue_radius = 2) {
  miss <- setdiff(c(x_col, y_col, gene_col), colnames(tx))
  if (length(miss)) stop("Columns not found in `tx`: ", paste(miss, collapse = ", "))
  if (!is.null(qv_col)) tx <- tx[tx[[qv_col]] >= qv_min, , drop = FALSE]
  gene <- as.character(tx[[gene_col]])
  if (is.null(genes)) genes <- sort(unique(gene))
  keep <- gene %in% genes
  x <- tx[[x_col]][keep]
  y <- tx[[y_col]][keep]
  gene <- gene[keep]
  if (is.null(bbox)) bbox <- c(min(x), max(x), min(y), max(y))
  nx <- max(1L, as.integer(ceiling((bbox[2] - bbox[1]) / bin_size)))
  ny <- max(1L, as.integer(ceiling((bbox[4] - bbox[3]) / bin_size)))
  ix <- pmin(pmax(floor((x - bbox[1]) / bin_size), 0), nx - 1)
  iy <- pmin(pmax(floor((y - bbox[3]) / bin_size), 0), ny - 1)
  bin <- ix + nx * iy + 1
  counts <- Matrix::sparseMatrix(i = bin, j = match(gene, genes), x = 1,
                                 dims = c(nx * ny, length(genes)),
                                 dimnames = list(NULL, genes))
  gx <- rep(seq_len(nx) - 1, times = ny)
  gy <- rep(seq_len(ny) - 1, each = nx)
  occupied <- matrix(Matrix::rowSums(counts) > 0, nx, ny)
  in_tissue <- if (is.infinite(tissue_radius)) {
    rep(TRUE, nx * ny)
  } else {
    as.vector(.dilate(occupied, tissue_radius))
  }
  structure(list(
    counts = counts,
    coords = data.frame(x = bbox[1] + (gx + 0.5) * bin_size,
                        y = bbox[3] + (gy + 0.5) * bin_size,
                        in_tissue = in_tissue),
    grid = list(nx = nx, ny = ny, bin_size = bin_size, xmin = bbox[1], ymin = bbox[3]),
    genes = genes
  ), class = "binned_transcripts")
}

# Internal: Gaussian smoothing of a grid (sigma in bins) by FFT, zero-padded.
.smooth_grid <- function(m, sigma) {
  nx <- nrow(m); ny <- ncol(m)
  ext <- ceiling(4 * sigma)
  px <- stats::nextn(nx + 2 * ext); py <- stats::nextn(ny + 2 * ext)
  pad <- matrix(0, px, py); pad[seq_len(nx), seq_len(ny)] <- m
  lag <- function(p) { k <- 0:(p - 1); ifelse(k < p / 2, k, k - p) }
  ker <- exp(-outer(lag(px)^2, lag(py)^2, "+") / (2 * sigma^2))
  ker <- ker / sum(ker)
  out <- Re(stats::fft(stats::fft(pad) * stats::fft(ker), inverse = TRUE)) / (px * py)
  out[seq_len(nx), seq_len(ny)]
}

# Internal: binary dilation of a logical matrix with a (2r+1) square.
.dilate <- function(m, r) {
  out <- m
  nx <- nrow(m); ny <- ncol(m)
  for (dx in -r:r) for (dy in -r:r) {
    xs <- seq_len(nx) + dx; ys <- seq_len(ny) + dy
    okx <- xs >= 1 & xs <= nx; oky <- ys >= 1 & ys <= ny
    out[okx, oky] <- out[okx, oky] | m[xs[okx], ys[oky]]
  }
  out
}

#' @export
print.binned_transcripts <- function(x, ...) {
  cat(sprintf("<binned_transcripts> %d x %d bins of %g (%d in tissue), %d genes, %d transcripts\n",
              x$grid$nx, x$grid$ny, x$grid$bin_size, sum(x$coords$in_tissue),
              length(x$genes), as.integer(sum(x$counts))))
  invisible(x)
}

# ---- Model-free cross pair correlation -----------------------------------

#' Empirical cross pair correlation of two gene sets (segmentation-free)
#'
#' **Experimental.** Estimate the cross pair
#' correlation function \eqn{g_{AB}(r)} between the transcripts of gene set
#' A and gene set B from binned counts, with FFT-based edge correction over
#' the in-tissue bins. \eqn{g_{AB}(r) > 1} means B transcripts are found at
#' distance `r` from A transcripts more often than under independence (the
#' continuous analogue of the neighborhood enrichment `log2_oe`).
#'
#' @param binned A `binned_transcripts` object from [bin_transcripts()].
#' @param set_a,set_b Character vectors of genes (B defaults to A, giving
#'   the auto pair correlation).
#' @param r_max Largest distance to report.
#' @param r_step Width of the distance annuli (default: the bin size).
#' @param relative If `TRUE`, divide by the pair correlation of all
#'   transcripts. This is the observed / expected ratio of A-B pairs at
#'   distance `r` when gene labels are permuted over the fixed transcript
#'   positions (the normalized mark connection function) - the
#'   segmentation-free counterpart of the label-permutation `log2_oe` of
#'   [nhood_enrichment()]. Variation in overall cellularity cancels in the
#'   ratio, so it is the recommended value for comparing samples.
#'
#' @return A data.frame with `r` (annulus midpoint), `g`, `log_g` and
#'   `n_lags` (number of grid lags averaged).
#' @export
#' @examples
#' tx <- simulate_transcripts(size = 150, rate = 0.01, coloc = c(A = 1, B = 1))
#' b <- bin_transcripts(tx, bin_size = 3)
#' genes_a <- unique(tx$gene[tx$gene_set == "A"])
#' genes_b <- unique(tx$gene[tx$gene_set == "B"])
#' head(pcf_cross(b, genes_a, genes_b, r_max = 30))
pcf_cross <- function(binned, set_a, set_b = set_a, r_max = 100,
                      r_step = binned$grid$bin_size, relative = FALSE) {
  if (!inherits(binned, "binned_transcripts")) stop("`binned` must come from bin_transcripts().")
  res <- .pcf_fft(binned, set_a, set_b, r_max, r_step)
  if (relative) {
    all_g <- .pcf_fft(binned, binned$genes, binned$genes, r_max, r_step)
    res$g <- res$g / all_g$g
    res$log_g <- log(res$g)
  }
  res
}

.pcf_fft <- function(binned, set_a, set_b, r_max, r_step) {
  g <- binned$grid
  nx <- g$nx; ny <- g$ny
  miss <- setdiff(c(set_a, set_b), binned$genes)
  if (length(miss)) stop("Genes not in the binned data: ", paste(miss, collapse = ", "))
  mask <- matrix(as.numeric(binned$coords$in_tissue), nx, ny)
  field <- function(genes) {
    matrix(Matrix::rowSums(binned$counts[, genes, drop = FALSE]), nx, ny) * mask
  }
  shared <- intersect(set_a, set_b)
  self <- if (length(shared)) sum(field(shared)) else 0
  .pcf_fields(field(set_a), field(set_b), mask, g$bin_size, r_max, r_step, self_pairs = self)
}

# Internal: annulus-averaged cross pair correlation of two non-negative
# fields on a grid (counts or intensities), edge-corrected over `mask`.
# `self_pairs` is subtracted at lag 0 (transcripts paired with themselves).
.pcf_fields <- function(fa, fb, mask, d, r_max, r_step, self_pairs = 0) {
  nx <- nrow(mask); ny <- ncol(mask)
  fa <- fa * mask; fb <- fb * mask
  px <- stats::nextn(2 * nx); py <- stats::nextn(2 * ny)
  pad <- function(m) { out <- matrix(0, px, py); out[seq_len(nx), seq_len(ny)] <- m; out }
  xcorr <- function(a, b) {
    Re(stats::fft(Conj(stats::fft(pad(a))) * stats::fft(pad(b)), inverse = TRUE)) / (px * py)
  }
  pairs <- xcorr(fa, fb)
  overlap <- xcorr(mask, mask)
  pairs[1, 1] <- pairs[1, 1] - self_pairs
  area_bins <- sum(mask)
  lam_a <- sum(fa) / area_bins
  lam_b <- sum(fb) / area_bins
  lag <- function(p) { k <- 0:(p - 1); ifelse(k < p / 2, k, k - p) }
  dist <- d * sqrt(outer(lag(px)^2, lag(py)^2, "+"))
  ok <- overlap > 0.5 & dist <= r_max + r_step / 2
  breaks <- seq(0, r_max + r_step, by = r_step)
  ann <- findInterval(dist[ok], breaks)
  obs <- tapply(pairs[ok], ann, sum)
  expd <- tapply(overlap[ok] * lam_a * lam_b, ann, sum)
  nl <- tapply(rep(1, sum(ok)), ann, sum)
  idx <- as.integer(names(obs))
  out <- data.frame(r = (breaks[idx] + breaks[idx + 1]) / 2,
                    g = as.numeric(obs / expd), n_lags = as.integer(nl))
  out$log_g <- log(pmax(out$g, .Machine$double.eps))
  out[out$r <= r_max, c("r", "g", "log_g", "n_lags")]
}

# ---- Random-feature LGCP factor model -------------------------------------

#' Fit a random-feature spatial factor model to binned transcripts
#'
#' **Experimental.** Segmentation-free model of
#' transcript counts. For in-tissue bin `b` (centre `u_b`, area `a`) and gene
#' `j`,
#' \deqn{y_{bj} \sim \mathrm{Poisson\ or\ NB}(\mu_{bj}), \quad
#'   \log\mu_{bj} = \log a + \alpha_j + \sigma_0 f_0(u_b) + \sum_{k=1}^K L_{jk} f_k(u_b),}
#' where \eqn{f_0} is a cellularity field shared by all genes and
#' \eqn{f_1,\dots,f_K} are spatial factors. Each field is a Gaussian process
#' with RBF covariance \eqn{\exp(-h^2/2\ell_k^2)} approximated by random
#' Fourier features, \eqn{f_k(u) = \phi_{\ell_k}(u)^\top\gamma_k} with
#' \eqn{\phi_\ell(u) = M^{-1/2}[\cos(\Omega u/\ell), \sin(\Omega u/\ell)]},
#' \eqn{\Omega \sim N(0, I)} and \eqn{\gamma_k \sim N(0, I)}
#' (Gundersen et al. 2021, with the coordinates as observed inputs). Loadings,
#' weights, length scales and dispersions are estimated jointly by MAP with
#' closed-form gradients (L-BFGS-B).
#'
#' @param binned A `binned_transcripts` object.
#' @param n_factors Number of spatial factors `K`.
#' @param lengthscales Initial length scales (recycled to `K`); spreading
#'   them over scales breaks the symmetry between factors.
#' @param density_lengthscale Initial length scale of the cellularity field
#'   (`NULL` to omit the field). Ignored when `offset = "smoothed_total"`.
#' @param offset How overall cellularity enters the model. `"area"` (bin
#'   area only; cellularity is modelled by the latent field \eqn{f_0}) or
#'   `"smoothed_total"`: the log of the observed total transcript density,
#'   Gaussian-smoothed with bandwidth `offset_bandwidth`, is used as offset
#'   and no cellularity field is fitted. The latter conditions on where
#'   transcripts are, like the label permutation of [nhood_enrichment()],
#'   so that the factors describe composition only; it is the recommended
#'   choice for `rff_pair_correlation(type = "composition")` in group
#'   comparisons.
#' @param offset_bandwidth Standard deviation (same unit as the coordinates)
#'   of the Gaussian kernel used for `offset = "smoothed_total"`.
#' @param offset_genes Genes whose transcripts define the smoothed total
#'   (default: all genes). With few cell types, conditioning on all
#'   transcripts also removes the co-localization of the tested sets; use
#'   reference genes that are not part of the tested pair (e.g. broadly
#'   expressed genes) instead.
#' @param n_features Number of random frequencies `M` (2M features).
#' @param family `"nb"` (negative binomial, gene-specific dispersion) or
#'   `"poisson"`.
#' @param max_iter Maximum L-BFGS-B iterations.
#' @param seed Random seed for the random features and initialization.
#' @param verbose Print optimizer progress.
#'
#' @return An object of class `spatial_rff_fit` with the estimates
#'   (`alpha`, `L`, `sigma0`, `lengthscales`, `density_lengthscale`, `gamma`,
#'   `dispersion`), the random frequencies, the genes and convergence
#'   information.
#' @references Gundersen GW, Zhang MM, Engelhardt BE (2021). Latent variable
#'   modeling with random features. AISTATS, PMLR 130.
#' @export
#' @examples
#' tx <- simulate_transcripts(size = 120, rate = 0.02, n_genes_per_set = 3)
#' b <- bin_transcripts(tx, bin_size = 6)
#' fit <- fit_spatial_rff(b, n_factors = 2, n_features = 32, max_iter = 50)
#' fit
fit_spatial_rff <- function(binned, n_factors = 3,
                            lengthscales = c(10, 25, 50, 100),
                            density_lengthscale = 100,
                            offset = c("area", "smoothed_total"),
                            offset_bandwidth = 10,
                            offset_genes = NULL,
                            n_features = 64,
                            family = c("nb", "poisson"),
                            max_iter = 500,
                            seed = 1,
                            verbose = FALSE) {
  family <- match.arg(family)
  offset <- match.arg(offset)
  if (!inherits(binned, "binned_transcripts")) stop("`binned` must come from bin_transcripts().")
  .local_seed(seed)
  if (offset == "smoothed_total") density_lengthscale <- NULL
  keep <- binned$coords$in_tissue
  Y <- as.matrix(binned$counts[keep, , drop = FALSE])
  U <- as.matrix(binned$coords[keep, c("x", "y")])
  U <- sweep(U, 2, colMeans(U))
  N <- nrow(Y); J <- ncol(Y); K <- n_factors; M <- n_features
  has_d <- !is.null(density_lengthscale)
  log_area <- 2 * log(binned$grid$bin_size)
  if (offset == "smoothed_total") {
    g <- binned$grid
    og <- if (is.null(offset_genes)) binned$genes else intersect(offset_genes, binned$genes)
    if (!length(og)) stop("None of `offset_genes` are in the binned data.")
    tot <- matrix(Matrix::rowSums(binned$counts[, og, drop = FALSE]), g$nx, g$ny)
    mask <- matrix(as.numeric(binned$coords$in_tissue), g$nx, g$ny)
    sm <- .smooth_grid(tot * mask, offset_bandwidth / g$bin_size) /
      pmax(.smooth_grid(mask, offset_bandwidth / g$bin_size), 1e-8)
    sm_all <- as.vector(sm)
    sm <- sm_all[keep]
    log_area <- log(sm + 0.01 * mean(sm)) - log(mean(sm))
    offset_grid <- log(sm_all + 0.01 * mean(sm)) - log(mean(sm))
  } else {
    offset_grid <- rep(log_area, nrow(binned$coords))
  }
  Omega <- matrix(stats::rnorm(M * 2), M, 2)
  Z <- U %*% t(Omega)                         # N x M
  s <- 1 / sqrt(M)
  ell_init <- rep_len(lengthscales, K)
  lo <- log(binned$grid$bin_size)
  hi <- log(max(diff(range(U[, 1])), diff(range(U[, 2])), 2 * binned$grid$bin_size))

  n_fields <- K + has_d
  idx <- list()
  pos <- 0
  add <- function(name, n) { idx[[name]] <<- pos + seq_len(n); pos <<- pos + n }
  add("alpha", J); add("L", J * K); add("gamma", n_fields * 2 * M); add("log_ell", n_fields)
  if (has_d) add("log_sigma0", 1)
  if (family == "nb") add("log_r", J)

  theta0 <- numeric(pos)
  theta0[idx$alpha] <- log(colSums(Y) + 0.5) - log(sum(exp(rep_len(log_area, N))))
  theta0[idx$L] <- stats::rnorm(J * K, sd = 0.1)
  theta0[idx$gamma] <- stats::rnorm(n_fields * 2 * M, sd = 0.1)
  ell_all <- c(if (has_d) density_lengthscale, ell_init)
  theta0[idx$log_ell] <- log(ell_all)
  if (has_d) theta0[idx$log_sigma0] <- log(0.3)
  if (family == "nb") theta0[idx$log_r] <- log(10)
  prior_ell_mean <- log(ell_all)
  lower <- rep(-Inf, pos); upper <- rep(Inf, pos)
  lower[idx$log_ell] <- lo; upper[idx$log_ell] <- hi
  if (family == "nb") { lower[idx$log_r] <- log(1e-2); upper[idx$log_r] <- log(1e4) }

  unpack <- function(th) {
    list(alpha = th[idx$alpha],
         L = matrix(th[idx$L], J, K),
         gamma = matrix(th[idx$gamma], 2 * M, n_fields),
         ell = exp(th[idx$log_ell]),
         sigma0 = if (has_d) exp(th[idx$log_sigma0]) else 0,
         r = if (family == "nb") exp(th[idx$log_r]) else NULL)
  }
  y_nz <- Y > 0
  lfy <- sum(lgamma(Y + 1))

  objgrad <- function(th) {
    p <- unpack(th)
    Fm <- matrix(0, N, n_fields)
    dF <- matrix(0, N, n_fields)   # ell * d f / d ell
    for (k in seq_len(n_fields)) {
      A <- Z / p$ell[k]
      cA <- cos(A); sA <- sin(A)
      gc <- p$gamma[seq_len(M), k]; gs <- p$gamma[M + seq_len(M), k]
      Fm[, k] <- s * (cA %*% gc + sA %*% gs)
      dF[, k] <- s * ((sA * A) %*% gc - (cA * A) %*% gs)
    }
    Lfull <- if (has_d) cbind(p$sigma0, p$L) else p$L
    eta <- log_area + matrix(p$alpha, N, J, byrow = TRUE) + Fm %*% t(Lfull)
    mu <- exp(eta)
    if (family == "poisson") {
      nll <- sum(mu) - sum(Y * eta) + lfy
      R <- mu - Y
    } else {
      rr <- matrix(p$r, N, J, byrow = TRUE)
      lr <- log(rr + mu)
      nll <- -sum(lgamma(Y + rr) - lgamma(rr) + rr * (log(rr) - lr) + Y * (eta - lr)) + lfy
      R <- (mu - Y) * rr / (rr + mu)
      g_logr <- -p$r * colSums(digamma(Y + rr) - digamma(rr) + log(rr) - lr + 1 - (rr + Y) / (rr + mu))
    }
    G <- R %*% Lfull                       # N x n_fields
    grad <- numeric(pos)
    grad[idx$alpha] <- colSums(R)
    RtF <- crossprod(R, Fm)                # J x n_fields
    fac <- if (has_d) seq_len(K) + 1 else seq_len(K)
    grad[idx$L] <- as.vector(RtF[, fac, drop = FALSE]) + th[idx$L]
    gg <- matrix(0, 2 * M, n_fields)
    for (k in seq_len(n_fields)) {
      A <- Z / p$ell[k]
      gg[, k] <- s * c(crossprod(cos(A), G[, k]), crossprod(sin(A), G[, k]))
    }
    grad[idx$gamma] <- as.vector(gg) + th[idx$gamma]
    grad[idx$log_ell] <- colSums(G * dF) + (th[idx$log_ell] - prior_ell_mean)
    if (has_d) {
      grad[idx$log_sigma0] <- p$sigma0 * sum(RtF[, 1]) + th[idx$log_sigma0] / 4
    }
    if (family == "nb") grad[idx$log_r] <- g_logr + (th[idx$log_r] - log(10)) / 9
    prior <- 0.5 * sum(th[idx$L]^2) + 0.5 * sum(th[idx$gamma]^2) +
      0.5 * sum((th[idx$log_ell] - prior_ell_mean)^2) +
      (if (has_d) th[idx$log_sigma0]^2 / 8 else 0) +
      (if (family == "nb") sum((th[idx$log_r] - log(10))^2) / 18 else 0)
    list(value = nll + prior, grad = grad)
  }

  cache <- new.env()
  fn <- function(th) { cache$res <- objgrad(th); cache$th <- th; cache$res$value }
  gr <- function(th) {
    if (!identical(cache$th, th)) cache$res <- objgrad(th)
    cache$res$grad
  }
  opt <- stats::optim(theta0, fn, gr, method = "L-BFGS-B", lower = lower, upper = upper,
                      control = list(maxit = max_iter, trace = as.integer(verbose)))
  p <- unpack(opt$par)
  # Identifiability: the scale of each field trades off against its loading.
  # Rescale every field to unit empirical variance over the in-tissue bins
  # and move the scale into the loadings (cf. the rescaling step of
  # Gundersen et al. 2021), so that L describes log-intensity covariance.
  field_sd <- vapply(seq_len(n_fields), function(k) {
    A <- Z / p$ell[k]
    stats::sd(s * (cos(A) %*% p$gamma[seq_len(M), k] + sin(A) %*% p$gamma[M + seq_len(M), k]))
  }, numeric(1))
  p$gamma <- sweep(p$gamma, 2, field_sd, "/")
  fac_sd <- if (has_d) field_sd[-1] else field_sd
  p$L <- sweep(p$L, 2, fac_sd, "*")
  if (has_d) p$sigma0 <- p$sigma0 * field_sd[1]
  # fitted (unit-variance) fields on the full grid, for plug-in covariances
  U_all <- sweep(as.matrix(binned$coords[, c("x", "y")]), 2,
                 colMeans(as.matrix(binned$coords[keep, c("x", "y")])))
  Z_all <- U_all %*% t(Omega)
  field_grid <- vapply(seq_len(n_fields), function(k) {
    A <- Z_all / p$ell[k]
    as.vector(s * (cos(A) %*% p$gamma[seq_len(M), k] + sin(A) %*% p$gamma[M + seq_len(M), k]))
  }, numeric(nrow(U_all)))
  field_grid <- matrix(field_grid, ncol = n_fields)
  colnames(field_grid) <- c(if (has_d) "density", paste0("factor", seq_len(K)))
  rownames(p$L) <- colnames(Y)
  colnames(p$L) <- paste0("factor", seq_len(K))
  names(p$alpha) <- colnames(Y)
  structure(list(
    alpha = p$alpha, L = p$L, sigma0 = p$sigma0,
    lengthscales = if (has_d) p$ell[-1] else p$ell,
    density_lengthscale = if (has_d) p$ell[1] else NA_real_,
    gamma = p$gamma, dispersion = if (!is.null(p$r)) stats::setNames(p$r, colnames(Y)) else NULL,
    Omega = Omega, family = family, genes = colnames(Y), n_bins = N,
    field_grid = field_grid, grid = binned$grid, in_tissue = keep,
    offset_grid = offset_grid,
    bin_size = binned$grid$bin_size, has_density = has_d,
    objective = opt$value, convergence = opt$convergence, message = opt$message,
    iterations = opt$counts, offset = offset
  ), class = "spatial_rff_fit")
}

#' @export
print.spatial_rff_fit <- function(x, ...) {
  cat(sprintf("<spatial_rff_fit> %s model, %d genes, %d bins, %d factors\n",
              x$family, length(x$genes), x$n_bins, ncol(x$L)))
  cat("  factor length scales:", paste(signif(x$lengthscales, 3), collapse = ", "), "\n")
  if (x$has_density) {
    cat(sprintf("  cellularity field: sd %.2f, length scale %.3g\n",
                x$sigma0, x$density_lengthscale))
  }
  cat(sprintf("  convergence: %d (%s)\n", x$convergence, x$message))
  invisible(x)
}

#' Model-based cross pair correlation from a fitted random-feature LGCP
#'
#' **Experimental.** Under an LGCP the pair correlation of genes `j` and
#' `j'` is \eqn{g_{jj'}(h) = \exp(C_{jj'}(h))}, with \eqn{C_{jj'}} the
#' cross-covariance of their log-intensities. From the fit,
#' \eqn{C_{jj'}(h) = \tilde L_j \hat\Sigma(h) \tilde L_{j'}^\top}, where
#' \eqn{\tilde L} are the loadings (with \eqn{\sigma_0} for the cellularity
#' field) and \eqn{\hat\Sigma(h)} is the empirical cross-covariance matrix
#' of the fitted unit-variance fields at distance `h` (plug-in estimate).
#' Using the fields' actual cross-covariances, rather than assuming
#' independent factors, keeps the estimate correct when fitted factors are
#' correlated. For gene sets, gene pairs are weighted by their expected
#' intensities.
#'
#' Three summaries are available:
#' * `"relative"`: \eqn{g_{AB}(h) / g_{TT}(h)}, with T all modelled
#'   transcripts - the model-based counterpart of
#'   `pcf_cross(relative = TRUE)` and of the label-permutation `log2_oe`.
#' * `"full"`: \eqn{g_{AB}(h)}, including the shared cellularity field.
#' * `"composition"`: \eqn{g_{AB}(h)} without the cellularity field.
#'
#' **Which summary to compare between groups.** In simulations (6 vs 6
#' samples, Wilcoxon test):
#' * `pcf_cross(relative = TRUE)` (model-free) detected a planted change and
#'   stayed calibrated when groups differed only in cellularity
#'   heterogeneity; `"full"` gave false positives.
#' * `type = "composition"` with the default `method = "intensity"` and
#'   `offset = "area"` was calibrated and the most powerful when the panel
#'   contained many cell types (8 gene sets). With only 3 gene sets, two of
#'   which co-localize, the shared niche is hard to tell from the
#'   cellularity field and occasional false positives remained; there, fit
#'   with `offset = "smoothed_total"` and `offset_genes` set to reference
#'   genes outside the tested pair (calibrated, but less powerful).
#' * `method = "intensity"` estimates are shrunk towards 0 at short
#'   distances (conservative); `method = "gaussian"` is unbiased when the
#'   log-intensities are Gaussian but was badly miscalibrated on real Xenium
#'   data.
#'
#' @param fit A `spatial_rff_fit` from [fit_spatial_rff()].
#' @param set_a,set_b Character vectors of genes.
#' @param r Distances.
#' @param type `"relative"` (default), `"full"` or `"composition"`.
#' @param method `"intensity"` (default): apply the FFT pair-correlation
#'   estimator of [pcf_cross()] to the fitted intensity surfaces
#'   \eqn{\hat\lambda_j(u)} - a denoised version of the empirical estimate
#'   that makes no Gaussian assumption. `"gaussian"`: the closed-form LGCP
#'   value \eqn{\exp(C_{jj'}(h))}, which is exact for Gaussian log-intensity
#'   fields but can be far off for sparse, strongly clustered genes (vessels,
#'   meninges) in real tissue.
#'
#' @return A data.frame with `r`, `g`, `log_g`.
#' @export
#' @examples
#' tx <- simulate_transcripts(size = 120, rate = 0.02, n_genes_per_set = 3)
#' b <- bin_transcripts(tx, bin_size = 6)
#' fit <- fit_spatial_rff(b, n_factors = 2, n_features = 32, max_iter = 50)
#' rff_pair_correlation(fit, c("A_1", "A_2"), c("B_1", "B_2"), r = c(5, 10, 20))
rff_pair_correlation <- function(fit, set_a, set_b, r,
                                 type = c("relative", "full", "composition"),
                                 method = c("intensity", "gaussian")) {
  type <- match.arg(type)
  method <- match.arg(method)
  miss <- setdiff(c(set_a, set_b), fit$genes)
  if (length(miss)) stop("Genes not in the fit: ", paste(miss, collapse = ", "))
  if (method == "intensity") return(.rff_pcf_intensity(fit, set_a, set_b, r, type))
  Lfull <- if (fit$has_density) cbind(density = fit$sigma0, fit$L) else fit$L
  rownames(Lfull) <- fit$genes
  Cf <- .field_xcov(fit, r)                         # n_fields x n_fields x length(r)
  C0 <- .field_xcov(fit, 0)[, , 1]
  e_log <- fit$alpha + 0.5 * rowSums((Lfull %*% C0) * Lfull)
  w <- function(set) { v <- exp(e_log[set] - max(e_log[set])); v / sum(v) }
  keep_f <- if (type == "composition" && fit$has_density) -1 else seq_len(ncol(Lfull))
  pooled <- function(sa, sb, i, cols) {
    Ck <- Cf[cols, cols, i, drop = FALSE][, , 1]
    C <- Lfull[sa, cols, drop = FALSE] %*% Ck %*% t(Lfull[sb, cols, drop = FALSE])
    sum(outer(w(sa), w(sb)) * exp(C))
  }
  all_cols <- seq_len(ncol(Lfull))
  g <- vapply(seq_along(r), function(i) {
    switch(type,
      full = pooled(set_a, set_b, i, all_cols),
      composition = pooled(set_a, set_b, i, all_cols[keep_f]),
      relative = pooled(set_a, set_b, i, all_cols) / pooled(fit$genes, fit$genes, i, all_cols))
  }, numeric(1))
  data.frame(r = r, g = g, log_g = log(g))
}

# Internal: plug-in pair correlation of the fitted intensity surfaces.
# For type "composition" the cellularity field (offset = "area") or the
# smoothed-total offset (offset = "smoothed_total") is removed first.
.rff_pcf_intensity <- function(fit, set_a, set_b, r, type) {
  g <- fit$grid
  mask <- matrix(as.numeric(fit$in_tissue), g$nx, g$ny)
  Lfull <- if (fit$has_density) cbind(fit$sigma0, fit$L) else fit$L
  rownames(Lfull) <- fit$genes
  cols <- seq_len(ncol(Lfull))
  drop_cell <- type == "composition"
  if (drop_cell && fit$has_density) cols <- cols[-1]
  base <- if (drop_cell && identical(fit$offset, "smoothed_total")) 0 else fit$offset_grid
  intensity <- function(genes) {
    eta <- fit$field_grid[, cols, drop = FALSE] %*% t(Lfull[genes, cols, drop = FALSE])
    eta <- sweep(eta, 2, fit$alpha[genes], "+") + base
    matrix(rowSums(exp(eta)), g$nx, g$ny)
  }
  r_max <- max(r) + g$bin_size
  curve <- function(sa, sb) {
    .pcf_fields(intensity(sa), intensity(sb), mask, g$bin_size, r_max, g$bin_size)
  }
  pc <- curve(set_a, set_b)
  lg <- stats::approx(pc$r, pc$log_g, xout = r, rule = 2)$y
  if (type == "relative") {
    tt <- curve(fit$genes, fit$genes)
    lg <- lg - stats::approx(tt$r, tt$log_g, xout = r, rule = 2)$y
  }
  data.frame(r = r, g = exp(lg), log_g = lg)
}

# Internal: empirical cross-covariance of the fitted (centred) fields at
# distances r, averaged over annuli of one bin width, over in-tissue bins.
.field_xcov <- function(fit, r) {
  g <- fit$grid
  nx <- g$nx; ny <- g$ny; d <- g$bin_size
  mask <- matrix(as.numeric(fit$in_tissue), nx, ny)
  Fg <- fit$field_grid
  nf <- ncol(Fg)
  cen <- lapply(seq_len(nf), function(k) {
    v <- Fg[, k]; v <- v - mean(v[fit$in_tissue]); matrix(v, nx, ny) * mask
  })
  px <- stats::nextn(2 * nx); py <- stats::nextn(2 * ny)
  pad <- function(m) { out <- matrix(0, px, py); out[seq_len(nx), seq_len(ny)] <- m; out }
  fx <- lapply(cen, function(m) stats::fft(pad(m)))
  ov <- Re(stats::fft(Conj(stats::fft(pad(mask))) * stats::fft(pad(mask)), inverse = TRUE)) / (px * py)
  lag <- function(p) { k <- 0:(p - 1); ifelse(k < p / 2, k, k - p) }
  dist <- d * sqrt(outer(lag(px)^2, lag(py)^2, "+"))
  sel <- lapply(r, function(h) which(abs(dist - h) < d / 2 & ov > 0.5))
  out <- array(0, c(nf, nf, length(r)), dimnames = list(colnames(Fg), colnames(Fg), NULL))
  for (a in seq_len(nf)) for (b in a:nf) {
    xc <- Re(stats::fft(Conj(fx[[a]]) * fx[[b]], inverse = TRUE)) / (px * py)
    xc_t <- Re(stats::fft(Conj(fx[[b]]) * fx[[a]], inverse = TRUE)) / (px * py)
    for (i in seq_along(r)) {
      # symmetrize over +h / -h so that C(h) is a symmetric matrix
      v <- 0.5 * (sum(xc[sel[[i]]]) + sum(xc_t[sel[[i]]])) / sum(ov[sel[[i]]])
      out[a, b, i] <- out[b, a, i] <- v
    }
  }
  out
}

# ---- Multi-sample wrapper --------------------------------------------------

#' Per-sample segmentation-free co-localization of gene sets
#'
#' **Experimental.** For every sample, bin the
#' transcripts and compute the log cross pair correlation between gene sets
#' at the requested distances, either model-free ([pcf_cross()]) or from a
#' fitted random-feature LGCP ([fit_spatial_rff()] +
#' [rff_pair_correlation()]). The tidy output goes straight into
#' [compare_groups()] with `value = "log_g"` and
#' `pair_keys = c("cluster_i", "cluster_j", "r")`.
#'
#' @param tx Transcript table with a sample column.
#' @param sample_key,group_key,patient_key Column names.
#' @param gene_sets Named list of gene vectors (e.g. cell-type markers).
#' @param pairs Two-column data.frame or list of length-2 character vectors
#'   of gene-set names to test (default: all unordered pairs, including
#'   self-pairs).
#' @param r Distances at which to report `log_g`.
#' @param method `"empirical"` or `"model"`.
#' @param bin_size Bin size passed to [bin_transcripts()].
#' @param relative For `method = "empirical"`: if `TRUE` (default), report
#'   the relative pair correlation (label-permutation O/E; see
#'   [pcf_cross()]), which is robust to differences in overall cellularity
#'   between samples.
#' @param model_type For `method = "model"`: the `type` passed to
#'   [rff_pair_correlation()] (default `"composition"`).
#' @param n_cores Number of samples processed in parallel (forked
#'   processes via [parallel::mclapply()]; sequential on Windows).
#' @param ... Passed to [fit_spatial_rff()] (for `method = "model"`) or
#'   [bin_transcripts()].
#'
#' @return A data.frame with `sample_id`, `cluster_i`, `cluster_j`, `r`,
#'   `log_g`, `n_transcripts`, `group`, `patient`.
#' @export
#' @examples
#' tx <- simulate_transcripts_groups(n_samples_per_group = 2, size = 120,
#'                                   rate = 0.01)
#' sets <- split(unique(tx[, c("gene", "gene_set")])$gene,
#'               unique(tx[, c("gene", "gene_set")])$gene_set)
#' res <- colocalization_per_sample(tx, "sample_id", "group", "patient",
#'                                  gene_sets = sets,
#'                                  pairs = list(c("A", "B")), r = c(10, 20))
#' res
colocalization_per_sample <- function(tx, sample_key, group_key, patient_key = NULL,
                                      gene_sets, pairs = NULL, r = c(10, 25, 50),
                                      method = c("empirical", "model"),
                                      bin_size = 4, relative = TRUE,
                                      model_type = c("composition", "relative", "full"),
                                      n_cores = 1, ...) {
  method <- match.arg(method)
  model_type <- match.arg(model_type)
  if (is.null(names(gene_sets)) || any(names(gene_sets) == "")) stop("gene_sets must be a named list.")
  if (is.null(pairs)) {
    nm <- names(gene_sets)
    pairs <- do.call(rbind, lapply(seq_along(nm), function(i) {
      data.frame(a = nm[i], b = nm[seq(i, length(nm))], stringsAsFactors = FALSE)
    }))
  } else if (is.list(pairs) && !is.data.frame(pairs)) {
    pairs <- data.frame(a = vapply(pairs, `[`, "", 1), b = vapply(pairs, `[`, "", 2),
                        stringsAsFactors = FALSE)
  }
  pairs <- stats::setNames(as.data.frame(pairs, stringsAsFactors = FALSE)[, 1:2], c("a", "b"))
  dots <- list(...)
  bin_args <- dots[intersect(names(dots), names(formals(bin_transcripts)))]
  fit_args <- dots[intersect(names(dots), names(formals(fit_spatial_rff)))]
  all_genes <- unique(unlist(gene_sets))
  one_sample <- function(sid) {
    rows <- list()
    sub <- tx[as.character(tx[[sample_key]]) == sid, , drop = FALSE]
    b <- do.call(bin_transcripts, c(list(sub, bin_size = bin_size,
                                         genes = intersect(all_genes, unique(sub$gene))),
                                    bin_args))
    fit <- if (method == "model") do.call(fit_spatial_rff, c(list(b), fit_args)) else NULL
    for (q in seq_len(nrow(pairs))) {
      ga <- intersect(gene_sets[[pairs$a[q]]], b$genes)
      gb <- intersect(gene_sets[[pairs$b[q]]], b$genes)
      if (!length(ga) || !length(gb)) next
      lg <- if (method == "empirical") {
        pc <- pcf_cross(b, ga, gb, r_max = max(r) + bin_size, relative = relative)
        stats::approx(pc$r, pc$log_g, xout = r, rule = 2)$y
      } else {
        rff_pair_correlation(fit, ga, gb, r, type = model_type)$log_g
      }
      rows[[length(rows) + 1L]] <- data.frame(
        sample_id = sid, cluster_i = pairs$a[q], cluster_j = pairs$b[q], r = r,
        log_g = lg, n_transcripts = nrow(sub),
        group = as.character(sub[[group_key]][1]),
        patient = if (is.null(patient_key)) NA_character_ else as.character(sub[[patient_key]][1]),
        stringsAsFactors = FALSE
      )
    }
    do.call(rbind, rows)
  }
  sids <- unique(as.character(tx[[sample_key]]))
  rows <- if (n_cores > 1 && .Platform$OS.type != "windows") {
    parallel::mclapply(sids, one_sample, mc.cores = n_cores)
  } else {
    lapply(sids, one_sample)
  }
  out <- do.call(rbind, rows)
  attr(out, "value_columns") <- "log_g"
  class(out) <- c("spatialCooccurSample", class(out))
  out
}
